version: "3.9"
services:
  postgre:
    image: postgres:12
    container_name: postgres
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "tutorial"
