version: "3.9"
services:
  postgre:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "tutorial"
      POSTGRES_USER: "tutorial"
      POSTGRES_DB: "tutorial"
      POSTGRES_HOST_AUTH_METHOD: trust
  adminer:
    image: adminer
    restart: always
    container_name: postgres-adminer
    ports:
      - 8080:8080

